### PR TITLE
[DNM] Test torch2 on gpu v2

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by mikemhenry** [comment]
Interesting, only getting two failures:

```
FAILED TestInteroperability.py::testTorchANI[CUDA-True] - openmm.OpenMMException: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/TestInteroperability/___torch_mangle_17.py", line 14, in forward
    model = self.model
    atomic_numbers = self.atomic_numbers
    _1 = (model).forward((atomic_numbers, positions0), None, None, )
          ~~~~~~~~~~~~~~ <--- HERE
    _2 = torch.mul(torch.select((_1)[1], 0, 0), 2625.5)
    return _2
  File "code/__torch__/NNPOps/OptimizedTorchANI.py", line 17, in forward
    species_coordinates0 = (species_converter).forward(species_coordinates, None, None, )
    aev_computer = self.aev_computer
    species_aevs = (aev_computer).forward(species_coordinates0, cell, pbc, )
                    ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    neural_networks = self.neural_networks
    species_energies = (neural_networks).forward(species_aevs, )
  File "code/__torch__/NNPOps/SymmetryFunctions.py", line 39, in forward
    _4 = ops.NNPOpsANISymmetryFunctions.operation(holder, torch.select(positions, 0, 0), cell0)
    radial, angular, = _4
    features = torch.unsqueeze(torch.cat([radial, angular], 1), 0)
                               ~~~~~~~~~ <--- HERE
    return (species, features)

Traceback of TorchScript, original code (most recent call last):
  File "/actions-runner/_work/openmm-torch/openmm-torch/python/tests/TestInteroperability.py", line 31, in forward
        def forward(self, positions):
            positions = positions.float().unsqueeze(0) * 10 # nm --> Ang
            return self.model((self.atomic_numbers, positions)).energies[0] * 2625.5 # Hartree --> kJ/mol
                   ~~~~~~~~~~ <--- HERE
  File "/home/ec2-user/micromamba-root/envs/build/lib/python3.10/site-packages/NNPOps/OptimizedTorchANI.py", line 52, in forward
    
        species_coordinates = self.species_converter(species_coordinates)
        species_aevs = self.aev_computer(species_coordinates, cell=cell, pbc=pbc)
                       ~~~~~~~~~~~~~~~~~ <--- HERE
        species_energies = self.neural_networks(species_aevs)
        species_energies = self.energy_shifter(species_energies)
  File "/home/ec2-user/micromamba-root/envs/build/lib/python3.10/site-packages/NNPOps/SymmetryFunctions.py", line 121, in forward
    
        radial, angular = operation(self.holder, positions[0], cell)
        features = torch.cat((radial, angular), dim=1).unsqueeze(0)
                   ~~~~~~~~~ <--- HERE
    
        return species, features
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
FAILED TestInteroperability.py::testTorchANI[CUDA-False] - openmm.OpenMMException: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/TestInteroperability/___torch_mangle_18.py", line 14, in forward
    model = self.model
    atomic_numbers = self.atomic_numbers
    _1 = (model).forward((atomic_numbers, positions0), None, None, )
          ~~~~~~~~~~~~~~ <--- HERE
    _2 = torch.mul(torch.select((_1)[1], 0, 0), 2625.5)
    return _2
  File "code/__torch__/NNPOps/OptimizedTorchANI.py", line 17, in forward
    species_coordinates0 = (species_converter).forward(species_coordinates, None, None, )
    aev_computer = self.aev_computer
    species_aevs = (aev_computer).forward(species_coordinates0, cell, pbc, )
                    ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    neural_networks = self.neural_networks
    species_energies = (neural_networks).forward(species_aevs, )
  File "code/__torch__/NNPOps/SymmetryFunctions.py", line 39, in forward
    _4 = ops.NNPOpsANISymmetryFunctions.operation(holder, torch.select(positions, 0, 0), cell0)
    radial, angular, = _4
    features = torch.unsqueeze(torch.cat([radial, angular], 1), 0)
                               ~~~~~~~~~ <--- HERE
    return (species, features)

Traceback of TorchScript, original code (most recent call last):
  File "/actions-runner/_work/openmm-torch/openmm-torch/python/tests/TestInteroperability.py", line 31, in forward
        def forward(self, positions):
            positions = positions.float().unsqueeze(0) * 10 # nm --> Ang
            return self.model((self.atomic_numbers, positions)).energies[0] * 2625.5 # Hartree --> kJ/mol
                   ~~~~~~~~~~ <--- HERE
  File "/home/ec2-user/micromamba-root/envs/build/lib/python3.10/site-packages/NNPOps/OptimizedTorchANI.py", line 52, in forward
    
        species_coordinates = self.species_converter(species_coordinates)
        species_aevs = self.aev_computer(species_coordinates, cell=cell, pbc=pbc)
                       ~~~~~~~~~~~~~~~~~ <--- HERE
        species_energies = self.neural_networks(species_aevs)
        species_energies = self.energy_shifter(species_energies)
  File "/home/ec2-user/micromamba-root/envs/build/lib/python3.10/site-packages/NNPOps/SymmetryFunctions.py", line 121, in forward
    
        radial, angular = operation(self.holder, positions[0], cell)
        features = torch.cat((radial, angular), dim=1).unsqueeze(0)
                   ~~~~~~~~~ <--- HERE
    
        return species, features
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Will need to google this a bit, all the other python CUDA tests pass so I don't think it is something like the GPU isn't supported

**Comment by mikemhenry** [comment]
Hmm, it might be a cuda compute thing. I will spin up an instance and see what CUDA version, driver, and card we are using.

**Comment by RaulPPelaez** [comment]
Yeah I am afraid you are seeing whatever I saw here:
https://github.com/openmm/openmm-torch/pull/106#issuecomment-1525105427
I do not know what causes this, but seems to arise only sometimes... Could you post the output of nvidia-smi?

**Comment by RaulPPelaez** [comment]
Also, this error is occurring in an NNPOps imported class, it just so happens that one of the openmm-torch tests uses it.

**Comment by mikemhenry** [comment]
Also I just ran the CI for NNPOps and it passed:
https://github.com/openmm/NNPOps/actions/runs/5063145679/jobs/9089458222
(looks like using pytorch2)

1) Maybe we are missing some test coverage in NNPOps?
2) Perhaps there is an issue with the conda-forge NNPOps package?

I can also play around with the AMI and see if there is one that supports a newer version of cuda so we can test 11.8 or something. I do wonder if the issue could be here: https://github.com/conda-forge/nnpops-feedstock/blob/main/recipe/build.sh 

Where I am too aggressive in which kernel binaries I don't build.

**Comment by RaulPPelaez** [comment]
I believe the issue might very well be in the script you linked. Compiling for a specific arch could cause this issue.
I can see this not being called, for instance if cuda_compiler_version is just "11":
https://github.com/conda-forge/nnpops-feedstock/blob/c024ffce22cfc7b4ae24280fa43a2c4d2dbd8eb3/recipe/build.sh#L20-L33
Which would cause seemingly arbitrary kernels to show "No kernel image is available".

There are other less manual ways to list archs if you can call nvcc:
1. Not available below CUDA 11
```shell
$ nvcc --list-gpu-arch
compute_35
compute_37
compute_50
compute_52
compute_53
compute_60
compute_61
compute_62
compute_70
compute_72
compute_75
compute_80
compute_86
compute_87
```
2. I have been using this since version 7.5, this is the output for 11.7
```shell
$ nvcc --help | awk '/--/{p=0}/Allowed/{p=1}p' | grep -Eo "compute\_[0-9]{2}" | sort | uniq
compute_35
compute_37
compute_50
compute_52
compute_53
compute_60
compute_61
compute_62
compute_70
compute_72
compute_75
compute_80
compute_86
compute_87
```
3. Not available below CUDA 11
```shell 
$ nvcc -arch=all
```

**Comment by mikemhenry** [comment]
Okay I will 
1) update the conda-forge recipe to try and build arches in a more comprehensive way. The history is a bit complicated, NVCC has evolved in how it works, we build multiple cuda versions so I can't use the latest nvcc options sometimes, and there is finite disk space on the CI box so we can't fill that up. I'm just mentioning this so you understand there is some history behind it and it wasn't just an oversight :)
2) Let's move the talk about the NNPOps tests to that issue you linked, I'd like to get that working as well and could use your help :)

**Comment by mikemhenry** [comment]
I want to get the tests working before I play with the conda-forge pacakge too much, but the more I look at it, I think the script should be building `7.5` for all the cuda versions

**Comment by mikemhenry** [comment]
Okay, that is good to know!

**Comment by RaulPPelaez** [comment]
@mikemhenry, should we close this and work on NNPops?

**Comment by mikemhenry** [comment]
Not sure how I missed this! Yes I don't think we need this anymore

**Pull request closed without merging**
