### PR TITLE
Improved coordination of CUDA contexts with PyTorch

### LINKED ISSUE #42: Simulation explodes after adding a TorchForce that is identical to zero
The following script simulates a simple system with 10 particles. The system has two forces: a simple harmonic bond force and a TorchForce. The forces applied on particles via the TorchForce is made into zeros, so the system with the TorchForce should be identical to that without the TorchForce. Without the TorchForce, simulations of the system is stable. After adding the TorchForce, simulation of the system explodes. This is strange because the TorchForce contributes nothing to the system.

```python
import torch
torch.set_default_dtype(torch.double)
import numpy as np
import simtk.openmm.app  as app
import simtk.openmm as omm
import simtk.unit as unit
from openmmtorch import TorchForce
import copy

class NNForceDihedral(torch.nn.Module):
    def __init__(self, num_dihedrals):
        super(NNForceDihedral, self).__init__()

	self.num_dihedrals = num_dihedrals
	self.fc1 = torch.nn.Linear(2*num_dihedrals, num_dihedrals)
        self.fc2 = torch.nn.Linear(num_dihedrals, 1, bias = False)

    def forward(self, dihedrals):
        x = torch.cat((torch.cos(dihedrals), torch.sin(dihedrals)), -1)
	x = torch.tanh(self.fc1(x))
        output = self.fc2(x)
        output = torch.squeeze(output)
	return output

class ForceModule(torch.nn.Module):
    def __init__(self, num_particles):
        super(ForceModule, self).__init__()
	self.num_particles = num_particles
	self.nnforce_dihedral = NNForceDihedral(num_particles - 3)

	self.index = torch.nn.Parameter(
            torch.LongTensor( [[i, i+1, i+2, i+3] for i in range(num_particles - 3)]),
            requires_grad = False
	)

    def forward(self, positions):
        xyz = torch.unsqueeze(positions, 0)

        xyz_i = torch.index_select(xyz, 1, self.index[:, 0])
        xyz_j = torch.index_select(xyz, 1, self.index[:, 1])
        xyz_k = torch.index_select(xyz, 1, self.index[:, 2])
        xyz_l = torch.index_select(xyz, 1, self.index[:, 3])

        b1 = xyz_i - xyz_j
        b2 = xyz_j - xyz_k
        b3 = xyz_l - xyz_k

        b1_cross_b2 = torch.cross(b1, b2)
        b3_cross_b2 = torch.cross(b3, b2)

        cos_d = torch.norm(b2, dim = -1)*torch.sum(b1_cross_b2*b3_cross_b2, -1)
        sin_d = torch.sum(b2*torch.cross(b3_cross_b2, b1_cross_b2), -1)

        dihedrals = torch.atan2(sin_d, cos_d)
        potential_energy = self.nnforce_dihedral(dihedrals)*torch.tensor(0.0)

        return potential_energy

xyz = torch.tensor([[ 1.357623  , -1.3806132 , -1.2257496 ],
                    [ 1.0385588 , -1.3198054 , -1.4279023 ],
                    [ 0.7484111 , -1.471794  , -1.6183405 ],
                    [ 0.6739166 , -1.2910188 , -1.9467432 ],
                    [ 0.33078226, -1.451046  , -1.9793787 ],
                    [ 0.15436828, -1.2586378 , -1.68369   ],
                    [ 0.42108235, -1.0122279 , -1.616695  ],
                    [ 0.4789558 , -1.1335697 , -1.2618917 ],
                    [ 0.8091399 , -1.080018  , -1.087149  ],
                    [ 0.97696364, -1.3592714 , -0.9014565 ]], requires_grad = True)

system_01 = omm.System()
system_0 = omm.System()
system_1 = omm.System()
for _ in range(10):
    system_01.addParticle(100)
    system_0.addParticle(100)
    system_1.addParticle(100)


harmonic_bond_force = omm.HarmonicBondForce()
for i in range(9):
    harmonic_bond_force.addBond(i, i+1, 0.38, 7e4)

harmonic_bond_force.setForceGroup(0)
system_01.addForce(copy.copy(harmonic_bond_force))
system_0.addForce(copy.copy(harmonic_bond_force))

force_module = ForceModule(10)

scripted_force_module = torch.jit.script(force_module)
scripted_force_module.save(f"./output/test/force_module.pth")
nnforce = TorchForce(f"./output/test/force_module.pth")
nnforce.setForceGroup(1)
system_01.addForce(copy.copy(nnforce))
system_1.addForce(copy.copy(nnforce))


T = 300*unit.kelvin
fricCoef = 1./unit.picoseconds
stepsize = 2. * unit.femtoseconds

## simulation with both forces
print("="*80)
print("Simulate system with both forces")
print("="*80)
integrator_01 = omm.LangevinMiddleIntegrator(T, fricCoef, stepsize)
platform_01 = omm.Platform.getPlatformByName('Reference')
context_01 = omm.Context(system_01, integrator_01, platform_01)
context_01.setPositions(xyz.data.numpy())

for i in range(1000):
    integrator_01.step(1)

    state = context_01.getState(getEnergy = True, getForces = True, groups = set([0]))
    bond_energy = state.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
    bond_force = state.getForces()
    bond_force = np.array(bond_force.value_in_unit(unit.kilojoule_per_mole/unit.nanometer))

    state = context_01.getState(getEnergy = True, getForces = True, groups = set([1]))
    torch_energy = state.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
    torch_force = state.getForces()
    torch_force = np.array(torch_force.value_in_unit(unit.kilojoule_per_mole/unit.nanometer))

    if (i + 1) % 50 == 0:
        print(f"step: {i:>5}, bond_energy: {bond_energy:>10.2f} kJ/mol, torch_energy: {torch_energy:>10.2f} kJ/mol, bond_force[0,0]:", bond_force[0,0], 'torch\
_force[0,0]: ', torch_force[0,0])

## simulation with only harmonic force
print("="*80)
print("Simulate system with just the harminic bond force")
print("="*80)

integrator_0 = omm.LangevinMiddleIntegrator(T, fricCoef, stepsize)
platform_0 = omm.Platform.getPlatformByName('Reference')
context_0 = omm.Context(system_0, integrator_0, platform_0)
context_0.setPositions(xyz.data.numpy())

for i in range(1000):
    integrator_0.step(1)

    state = context_0.getState(getEnergy = True, getForces = True, groups = set([0]))
    bond_energy = state.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
    bond_force = state.getForces()
    bond_force = np.array(bond_force.value_in_unit(unit.kilojoule_per_mole/unit.nanometer))

    if (i + 1) % 50 == 0:
        print(f"step: {i:>5}, bond_energy: {bond_energy:>10.2f} kJ/mol, bond_force[0,0]:", bond_force[0,0])

## simulation with only Torch force
print("="*80)
print("Simulate system with just the Torch force")
print("="*80)

integrator_1 = omm.LangevinMiddleIntegrator(T, fricCoef, stepsize)
platform_1 = omm.Platform.getPlatformByName('Reference')
context_1 = omm.Context(system_1, integrator_1, platform_1)
context_1.setPositions(xyz.data.numpy())

for i in range(1000):
    integrator_1.step(1)

    state = context_1.getState(getEnergy = True, getForces = True, groups = set([1]))
    torch_energy = state.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
    torch_force = state.getForces()
    torch_force = np.array(torch_force.value_in_unit(unit.kilojoule_per_mole/unit.nanometer))

    if (i + 1) % 50 == 0:
        print(f"step: {i:>5}, torch_energy: {torch_energy:>10.2f} kJ/mol, torch_force[0,0]: ", torch_force[0,0])
```

### PR DESCRIPTION
**Pull request by peastman**
Fixes #42.  This requires the changes from https://github.com/openmm/openmm/pull/3258.  We might want to wait a while before merging it, since it's not compatible with OpenMM 7.6.

### CODE REVIEW

**Comment by raimis** [comment]
`cuda-memcheck` reports several problems. I'll investigate them further. Meanwhile, I leave https://github.com/openmm/openmm/issues/3272 to you, @peastman.

**Comment by raimis** [comment]
https://github.com/peastman/openmm-torch/pull/1 might be a solution, but let me check after rebuilding everything.

**Comment by raimis** [comment]
The theory behind:
- We have two CUDA contexts and a results there two CUDA streams for each
- Switching between contexts, doesn't synchronise the streams. So an explicit synchronisation is required.

**Comment by raimis** [comment]
OpenMM 7.7b is out!

How shall we proceed with this? Can `conda-forge` build the beta of OpenMM-Torch using the OpenMM beta as a dependency?

**Comment by peastman** [comment]
Note that CI is failing because it's building against the released OpenMM.  I'm going to merge anyway, since it will be necessary for building a beta.

**Pull request merged**
