### PR TITLE
Fix the synchronisation between the CUDA contexts

### PR DESCRIPTION
**Pull request by raimis**
- [x] Synchronize the switching between CUDA contexts
- [x] Remove a redundant coping of forces

Related with #47

### CODE REVIEW

**Comment by raimis** [comment]
This requires OpenMM 7.7.

**Comment by peastman** [comment]
We can move forward with this now that 7.7 is out.  Is it ready for review?

**Comment by raimis** [comment]
@peastman this is ready!

**Comment by peastman** [comment]
Looks good.  It's going to cause conflicts with #52 though.  Since that's a much more complicated PR, can we get it merged first?

**Comment by raimis** [comment]
OK! #52 can go first, but let me review it on Monday.

**Comment by raimis** [comment]
@peastman this is ready for a review again!

**Comment by peastman** [comment]
Looks good.

**Pull request merged**
